# application.yml
spring:
  datasource:
    url: jdbc:mysql://192.168.2.188:3306/oauth2_db
    username: yangyang
    password: dsk16888..
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
      schema-locations:
        - classpath:db/oauth2-authorization-schema.sql
        - classpath:db/oauth2-registered-client-schema.sql
        - classpath:db/oauth2-authorization-consent-schema.sql

server:
  port: 9000