# application.yml
spring:
  datasource:
    url: jdbc:mysql://192.168.2.188:3306/oauth2_db
    username: yangyang
    password: dsk16888..
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource # 推荐 Druid 连接池
    druid:
      # 连接池大小配置
      initial-size: 5 # 初始化连接数
      min-idle: 5 # 连接池中保持的最小空闲连接数
      max-active: 20 # 连接池中允许的最大活动连接数
      max-wait: 60000

      # 连接检测配置
      time-between-eviction-runs-millis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000 # 配置一个连接在池中最小生存的时间，单位是毫秒
      validation-query: SELECT 1 # 用来检测连接是否有效的sql
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

      # 缓存配置
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20

      # 过滤器配置（用于统计和监控）
      filters: stat,wall,log4j
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
      schema-locations:
        - classpath:db/oauth2-authorization-schema.sql
        - classpath:db/oauth2-registered-client-schema.sql
        - classpath:db/oauth2-authorization-consent-schema.sql
# mybatis-plus配置
mybatis-plus:
  type-aliases-package: com.yy.domain  # 替换为你的实体类包名
  mapper-locations: classpath:mapper/*.xml # 指定Mapper XML文件路径
  configuration:
    map-underscore-to-camel-case: true  # 开启驼峰命名自动转换
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 打印SQL日志到控制台
server:
  port: 9000
logging:
  level:
    org:
      springframework:
        web:
          reactive:
            function:
              client: DEBUG